### ISSUE TITLE
Working without database

### ISSUE THREAD

**Issue by kirsazlid** [OmniLayer/omniapi#10]
Hello achamely,
I'm using local storage instead of database, so I didn't touch sql.conf which is used by api/sqltools.py. After running project, every time I send a request, there is a error message:
##########
WSGI app 0 (mountpoint='localhost|/v1/properties') ready in 1 seconds on interpreter 0xc25b50 pid: 58743
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./flask_rate_limit.py", line 67, in rate_limited
    return f(*args, **kwargs)
  File "./properties_service.py", line 68, in list
    return jsonify(rawlist())
  File "./properties_service.py", line 77, in rawlist
    ROWS= dbSelect("select PropertyData from smartproperties where Protocol != 'Fiat' ORDER BY PropertyName,PropertyID")
  File "./sqltools.py", line 51, in dbSelect
    dbInit()
  File "./sqltools.py", line 48, in dbInit
    dbc=con.cursor(cursor_factory=psycopg2.extras.DictCursor)
AttributeError: 'str' object has no attribute 'cursor'
localhost [pid: 58743|app: 0|req: 1/1] ::1 () {42 vars in 579 bytes} [Fri Jan 10 12:22:53 2020] GET /v1/properties/list => generated 0 bytes in 444 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
##############
This is because I'm not touching sql.conf, so in api/sqltools.py, function 'sql_connect()' returns a string instead of psycopg2.connect object, so in function 'dbInit()', variable con is also a string type, which has no cursor method.
What's the solution to this problem? Appreciating your reply.

**Comment by achamely** [comment]
@kirsazlid  unfortunately the omniapi project is not designed to use local storage. 
The entire project is designed to provide an api interface to data that is stored in a postgres database. 
It can not work without one.
